language: python
python: 3.6.7
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy download en
  - python -m spacy download en_core_web_sm
  - python -m spacy download en-coref-sm
  - python -c "import nltk; nltk.download('wordnet'); nltk.download('averaged_perceptron_tagger')"
  - python -c "import nltk; nltk.download('wordnet_ic'); nltk.download('punkt')"
# command to run tests
script:
  - pytest
